version: "3.9"
services:
  web:
    container_name: social-buddy-bot
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: sh -c "crond && rm -f tmp/pids/server.pid && bundle install && rails db:create && rails db:migrate && rails s -b 0.0.0.0"
    stdin_open: true
    tty: true
    restart: on-failure
    volumes:
      - ./web:/app
    ports:
      - "3333:3000"
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: ${RAILS_ENV}
      REDIS_URL_SIDEKIQ: ${REDIS_URL_SIDEKIQ}
      HOST: ${HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

  db:
    image: postgres:alpine3.18
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: redis:alpine3.18
    command: redis-server
    volumes:
      - ./tmp/redis:/data
  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: bundle exec sidekiq
    volumes:
      - './web:/app'
    environment:
      RAILS_ENV: ${RAILS_ENV}
      REDIS_URL_SIDEKIQ: ${REDIS_URL_SIDEKIQ}
